url: https://harishv7.github.io/singaithamizhan
baseurl: /agency-jekyll-theme/

# Site settings
title: Singai Thamizhan
email: singaithamizhan@mail.com
description: "A Community based project for Singapore Tamilians"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Kaushik Iyer
  pic: 1
  position: Leader & Founder
  social:
    - title: twitter
      url: #
    - title: facebook
      url: https://www.facebook.com/k.s.kaushik?fref=ts
    - title: stack-overflow
      url: #

- name: Harish Venkatesan
  pic: 2
  position: Creative Director
  social:
    - title: twitter
      url: #
    - title: facebook
      url: https://www.facebook.com/V.Harish
    - title: linkedin
      url: #

- name: Diana Petersen
  pic: 3
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url: http://www.fb.com/singaithamizhan2013
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
